package com.microservices.warehouse;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path = "/components", produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Iterable<Product> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path = "/components/{id}", produces = MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Optional<Product> getUserByID(@PathVariable Integer id) {
        // This returns a JSON or XML with the users
        return userRepository.findById(id);
    }
}